const WA="527352164501";
const SUPABASE_URL='https://ddfnrowhxsnyhqceglsm.supabase.co';
const SUPABASE_KEY='sb_publishable_qb8lMFVg3ZJO3W2jrw0pxg_8k_NTVR5';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const modal=document.getElementById("modal");
const views=["account","register","newClient","coverage","dashboard"];
let dashboardData=null, balanceHidden=false;
function openModal(view){views.forEach(v=>{const el=document.getElementById("view-"+v);if(el)el.classList.toggle("hidden",v!==view)});modal.classList.add("show");modal.setAttribute("aria-hidden","false");const first=modal.querySelector(".modal-view:not(.hidden) input");if(first)setTimeout(()=>first.focus(),40)}
function closeModal(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true")}
document.querySelectorAll("[data-open]").forEach(el=>el.addEventListener("click",()=>{if(el.dataset.plan){const p=document.getElementById("clientPlan");if(p)p.value=el.dataset.plan==='20/5'?'20/5':'10/2'}openModal(el.dataset.open)}));
document.querySelectorAll("[data-close]").forEach(el=>el.addEventListener("click",closeModal));
document.querySelectorAll("[data-switch]").forEach(el=>el.addEventListener("click",()=>openModal(el.dataset.switch)));
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("show"))closeModal()});
function val(form,name){return form.elements[name]?.value.trim()||""}
function goWA(text){window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,"_blank","noopener")}
function money(n){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n)||0)}
async function clientLogin(){const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;if(!email||!password)return;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return alert('No se pudo iniciar sesión: '+error.message);await linkAndLoadClient();}
async function linkAndLoadClient(){const {data:{user}}=await sb.auth.getUser();if(!user)return;let {data,error}=await sb.rpc('nexu_get_client_dashboard');if(error)return alert('No se pudo cargar tu cuenta: '+error.message);if(!data?.client){const phone=prompt('Para vincular tu cuenta con tu servicio TRON, escribe el WhatsApp registrado en tu contrato:');if(phone){const r=await sb.rpc('nexu_link_client_account',{p_email:user.email,p_phone:phone});if(r.error)return alert('No se pudo vincular: '+r.error.message);({data,error}=await sb.rpc('nexu_get_client_dashboard'));if(error)return alert('No se pudo cargar tu cuenta: '+error.message)}}if(!data?.client)return alert('No encontramos un cliente activo con ese correo y teléfono. Pide al administrador que agregue tu correo electrónico a tu ficha.');dashboardData=data;balanceHidden=false;renderDashboard();openModal('dashboard')}
function renderDashboard(){const c=dashboardData.client;document.getElementById('dashName').textContent='Hola, '+(c.name||'cliente');document.getElementById('dashPlan').textContent=`${c.plan||'—'} · ${money(c.price)}/mes`;document.getElementById('dashBalance').textContent=balanceHidden?'••••••':money(c.balance);document.getElementById('dashMonths').innerHTML=(dashboardData.months||[]).map(m=>`<div class="dash-row"><div><b>${m.label}</b><small>${m.status}</small></div><strong>${balanceHidden?'••••':money(m.remaining)}</strong></div>`).join('')||'<div class="notice">No hay mensualidades pendientes.</div>';document.getElementById('dashMessage').textContent='Aquí podrás consultar tu saldo y solicitar un cambio de plan. Los cambios de plan requieren autorización de TRON.'}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();await clientLogin()});
document.getElementById('registerForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,name=val(f,'name'),email=val(f,'email').toLowerCase(),phone=val(f,'phone').replace(/\D/g,'').slice(-10),pass=f.elements['password'].value;if(pass.length<8)return alert('La contraseña debe tener al menos 8 caracteres.');try{const {data,error}=await sb.auth.signUp({email,password:pass});if(error)throw error;await sb.rpc('nexu_register_client_account_request',{p_auth_user_id:data.user?.id||null,p_name:name,p_email:email,p_phone:phone});alert(data.session?'Cuenta creada. Ahora inicia sesión.':'Cuenta creada. Revisa tu correo si se solicita confirmación y después inicia sesión.');openModal('account')}catch(e){alert('No se pudo registrar la cuenta: '+e.message)}});
document.getElementById('clientForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const payload={p_name:val(f,'name'),p_phone:val(f,'phone'),p_email:val(f,'email'),p_city:val(f,'city'),p_address:val(f,'address'),p_reference:val(f,'reference'),p_plan:val(f,'plan')};try{const {error}=await sb.rpc('public_submit_installation',payload);if(error)throw error;alert('Solicitud enviada correctamente. TRON revisará cobertura y se comunicará contigo.');closeModal()}catch(err){alert('No se pudo enviar la solicitud: '+err.message)}});
document.getElementById('coverageForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;goWA(`Hola TRON Internet, quiero consultar cobertura.\n\nNombre: ${val(f,'name')}\nWhatsApp: ${val(f,'phone')}\nLocalidad: ${val(f,'city')}\nDirección: ${val(f,'address')}`);closeModal()});
document.getElementById('changePlanBtn').addEventListener('click',async()=>{const plan=prompt('Escribe el plan que quieres solicitar: 10/2 o 20/5','20/5');if(!['10/2','20/5'].includes(plan))return alert('Selecciona 10/2 o 20/5.');try{const {error}=await sb.rpc('nexu_submit_plan_change',{p_requested_plan:plan});if(error)throw error;alert('Solicitud enviada. TRON revisará y te confirmará el cambio.')}catch(e){alert('No se pudo enviar la solicitud: '+e.message)}});
document.getElementById('hideBalanceBtn').addEventListener('click',()=>{balanceHidden=!balanceHidden;renderDashboard()});
document.getElementById('clientLogoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();dashboardData=null;closeModal()});
document.getElementById('year').textContent=new Date().getFullYear();
